config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  root 'home#index'
 
  resources :comments
  resources :images
  resources :messages
  resources :presentations
  resources :videos
 
  get '/galeria' => 'images#index', as: 'gallery'
  get '/terminos' => 'home#terms', as: 'terms'
  get '/subir_imagen' => 'images#new', as: 'upload_img'
  get '/admin' => 'home#admin', as: 'admin'
 
  post '/create_message' => 'messages#create', as: 'create_message'
  post '/create_comment' => 'comments#create', as: 'create_comment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, presence: true
  validates :message, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  attr_accessor :title, :bytes, :image, :image_cache

  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { minumum: 4, maximum: 80 }
  validates :email, presence: true
  validates :text, presence: true
end

app/models/presentation.rb
class Presentation < ApplicationRecord
  validates :site, presence: true
  validates :datetime, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def authenticate_admin_key(key)
    if key == "anmariazea2017"
      return true
    else
      return false
    end
  end
end

app/models/video.rb
class Video < ApplicationRecord
  validates :route, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html
        format.json { render json: @comment.to_json }
      else
        format.html { render redirect_to: '/' }
        format.json { render json: @comment.errors }
      end
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end
  def index
    @comments = Comment.order(created_at: :desc)
  end
  def new
    @comment = Comment.new
  end
  def show
    @comment = Comment.find(params[:id])
  end

  private
    def comment_params
      params.require(:comment).permit(:name, :email, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = Message.new
    @images = Image.all().limit(5)
  end
  def terms
  end
  def admin
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
		puts image_params
    @image = Image.new(image_params)
    if !@image.save
      @error = @image.errors.full_messages.join('. ')
    end
    redirect_to gallery_path
  end
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    redirect_to gallery_path
  end
  def edit
    @image = Image.find(params[:id])
  end
  def index
		@images = Image.all
		respond_to do |format|
			format.html # Show index.html.erb
			format.json { render json: [@images, user_signed_in?] }
		end
  end
  def new
    @image = Image.new(title: "Imagen\##{1 + (Image.maximum(:id) || 0)}")
  end
  def show
    @image = Image.find(params[:id])
		respond_to do |format|
			format.json { render json: @image }
		end
  end
  def update
    @image = Image.find(params[:id])
    @image.update(image_params)

    redirect_to gallery_path
  end

  protected
  def direct_upload_mode?
    params[:direct].present?
  end

  def unsigned_mode?
    params[:unsigned].present?
  end

  private
    def image_params
      params.require(:image).permit(:image, :title)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to home_path, notice: "{parama[:name]} Su mensaje ha sido enviado" }
        format.json { render json: @message.to_json }
      else
        format.html { render redirect_to: '/' }
        format.json { render json: @message.errors }
      end
    end
  end
  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_path
  end
  def index
    @messages = Message.all
  end
  def new
    @message = Message.new
  end
  def show
    @message = Message.find(params[:id])
  end

  private
    def message_params
      params.require(:message).permit(:name, :email, :number, :text)
    end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  def create
    @presentation = Presentation.new(presentation_params)
    @presentation.save
    redirect_to presentations_path
  end
  def destroy
    @presentation = Presentation.find(params[:id])
    @presentation.destroy

    redirect_to presentations_path
  end
  def edit
    @presentation = Presentation.find(params[:id])
  end
  def index
     @presentations = Presentation.order(datetime: :asc)
  end
  def new
    @presentation = Presentation.new
  end
  def show
    @presentation = Presentation.find(params[:id])
  end
  def update
    @presentation = Presentation.find(params[:id])
    @presentation.update(presentation_params)

    redirect_to presentations_path
  end

  private
    def presentation_params
      params.require(:presentation).permit(:title, :site, :datetime, :contributors, :comment)
    end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    def new
      super
    end
    def create
      @user = User.new
      if @user.authenticate_admin_key(params[:clave])
        super
      else
        flash[:notice] = 'La clave de administración no es válida.'
        redirect_to root_path
      end
    end
    def edit
      super
    end
    def destroy
      super
    end
    def update
      super
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def create
    @video = Video.new(video_params)
    @video.save
    redirect_to videos_path
  end
  def destroy
    @video = Video.find(params[:id])
    @video.destroy
  end
  def edit
    @video = Video.find(params[:id])
  end
  def index
     @videos = Video.order(created_at: :desc)
  end
  def new
    @video = Video.new
  end
  def show
    @video = Video.find(params[:id])
  end
  def update
    @video = Video.find(params[:id])
    @video.update(video_params)

    redirect_to videos_path
  end

  private
    def video_params
      params.require(:video).permit(:title, :route, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def embed(url)
    url = url.to_s
    if url.include? "youtu"
      youtube_id = url.split("/").last
      puts youtube_id
      content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}", frameborder: "0")
    end
  end
end

app/views/comments/index.html.erb
<header>
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">Comentarios</div>
    </div>
  </div>
</header>

<section id="comentarios">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= form_tag(create_comment_path, id: "commentsForm") do -%>
          <div class="row">
            <div class="col-xs-12 col-md-6">
              <div class="form-group">
                <%= label_tag('comment[name]', 'Tu nombre *') %>
                <%= text_field_tag('comment[name]', nil, class: "form-control") %>
              </div>
              <div class="form-group">
                <%= label_tag('comment[email]', 'Tu correo electrónico') %>
                <%= email_field_tag('comment[email]', nil, class: "form-control") %>
              </div>
            </div>
            <div class="col-xs-12 col-md-6">
              <div class="form-group">
                <%= label_tag('comment[message]',  'Mensaje *') %>
                <%= text_area_tag('comment[message]', nil, class: "form-control") %>
              </div>
              <div class="success">
                <%= submit_tag('Publicar', class: "btn btn-md btn-primary") %>
              </div>
            </div>
          </div>
        <% end -%>

        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">comentarios</h3>
          </div>
          <% if @comments != [] %>
            <ul class="list-group" id="commentsList">
              <% @comments.each do |comment| %>
                <li class="list-group-item">
                  <h3><%= comment.name %></h3><br>
                  <p><%= comment.message %></p>
                </li>
              <% end %>
            </ul>
          <% else %>
            <ul class="list-group" id="commentsList"></ul>
            <span>Por ahora no hay comentarios.</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/admin.html.erb
<section id="administracion">
  <div class="container" style="background-color: rgba(255, 255, 255, .75);">
    <div class="row">
      <div class="col-xs-12">
        <h2>Aministración</h2>
        
        <% if not user_signed_in? %>
          <div class="form-group">
            <%= link_to 'Iniciar sesión', new_user_session_path, class: "btn btn-lg btn-primary" %>
          </div>
          <div class="form-group">
            <%= link_to 'Registro', new_user_registration_path, class: "btn btn-lg btn-primary" %>
          </div>
        <% else %>
          <p>Ya has iniciado sesión de administrador</p>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<!-- Header -->
<header class="parallax">
  <div class="container">
    <div class="intro-text">
      <div class="intro-heading">Grupo musical</div>
      <div class="intro-heading">Alegría Navideña</div>
      <div class="intro-lead-in">Nana Nanita Ea</div>
    </div>
  </div>
</header>

<!-- Services Section -->
<section id="presentacion" class="filled">
  <a href="#" class="page-scroll"></a>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Quienes somos</h2>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-xs-12">
        <p>
          Somos un grupo de jovenes y niños, que buscan llenar de alegría, llevando a un niño jesús vivo, en los corazones de aquellos que han perdido la ilusión del verdadero sentido del espiritu navideño.
        </p>
      </div>
    </div>
  </div>
</section>

<section id="info">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-center">
        <h3>MISIÓN</h3>
        <p>
          Llevar (entregar) a todos los niños, niñas y adultos a los que pueda llegar el musical navideño, un mensaje de amor, alegría y fraternidad a través de las expresiones artísticas de la música, teatro y el baile.
        </p>
        <h3>VISIÓN</h3>
        <P>
         El musical Alegría Navideña será en el año 2018 un proyecto de carácter profesional y podrá presentarse en los escenarios a nivel nacional.
        </P>
        <h3>HISTORIA</h3>
        <p>
          Este hermoso proyecto nació de la iniciativa y la visión de María Zea, una joven líder de la comunidad parroquial de San Cipriano del municipio de Bello en el año 2008. Y  que  actualmente está al frente del musical navideño, se atrevió a soñar con la manera de llevar un mensaje de amor y esperanza a todos los niños, niñas y personas. Un mensaje que pudiera quedar en los corazones de todos aquellos que lo escucharan.
y fue asi con las personas talentosas del barrio, que se dio inicio a la preparación de las niñas y jóvenes participantes del musical.
        </p>
      </div>
    </div>
  </div>
</section>

<!-- Carrusel de imágenes -->
<% if @images != [] %>
<section id="carrusel" class="row">
  <div class="col-xs-12">
    <div id="main-carousel" class="carousel slide transparent" data-ride="carousel">
      <ol class="carousel-indicators">
        <% @images.each_with_index do |img,i| %>
          <% if i == 0 %>
            <li data-target="#main-carousel" data-slide-to="0" class="active"></li>
          <% else %>
            <li data-target="#main-carousel" data-slide-to="<%=i%>"></li>
          <% end %>
        <% end %>
      </ol>
      <div class="carousel-inner" role="listbox">
        <% @images.each_with_index do |img,i| %>
          <% if i == 0 %>
            <div class="item active">
              <%= cl_image_tag(img.image, width: 960, height: 720) %>
            </div>
          <% else %>
            <div class="item">
              <%= cl_image_tag(img.image, width: 960, height: 720) %>
            </div>
          <% end %>
        <% end %>
      </div>
      <a href="#main-carousel" class="left carousel-control" role="button" data-slide="prev">
        <span class="fa fa-angle-left" aria-hidden="true"></span>
        <span class="sr-only">Anterior</span>
      </a>
      <a href="#main-carousel" class="right carousel-control" role="button" data-slide="next">
        <span class="fa fa-angle-right" aria-hidden="true"></span>
        <span class="sr-only">Siguiente</span>
      </a>
    </div>
  </div>
</section>
<% end %>

<!-- Contacto -->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Contactanos</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= form_tag(create_message_path, id: "contactForm") do -%>
          <div class="row">
            <div class="col-xs-12 col-md-6">
              <div class="form-group">
                <%= text_field_tag('message[name]', nil, class: "form-control", placeholder: "Tu nombre *", id: "name", required: true) %>
              </div>
              <div class="form-group">
                <%= email_field_tag('message[email]', nil, class: "form-control", placeholder: "Tu correo electrónico *", id: "email", required: true) %>
              </div>
              <div class="form-group">
                <%= text_field_tag('message[number]', nil, class: "form-control", placeholder: "Tu número de contacto *", id: "name", required: true) %>
              </div>
            </div>
            <div class="col-xs-12 col-md-6">
              <div class="form-group">
                <%= text_area_tag('message[text]', nil, class: "form-control", placeholder: "Mensaje *", id: "text", required: true) %>
              </div>
            </div>
            <div class="col-xs-12 text-center">
              <div class="success">
                <%= submit_tag('Enviar mensaje', class: "btn btn-xl") %>
              </div>
            </div>
          </div>
        <% end -%>

        <div class="text-center" style="margin-top: 45px;">
          <p><strong>Maria Zea: </strong>Directora</p>
          <p><strong>Celular: </strong>3002525791</p>
          <p><strong>Correo electrónico: </strong>mariazea2010@hotmail.com</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/images/edit.html.erb
</section><section id="editar-imagen">
  <div class="container form-container">
    <div class="row">
      <div class="col-xs-12">
        <h1>Actualizar imágen</h1>

        <% if @image.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@image.errors.count, "error") %> no permitieron que esta imágen se halla actualizado:</h2>

            <ul>
            <% @image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

				<%= cl_image_tag(@image.image, :alt => @image.title, style: "width: 424px;") %>
        <%= form_for(@image) do |f| %>
          <div class="form-group">
            <%= f.label :title, 'Título' %>
            <%= f.text_field :title, placeholder: "Título de la imágen", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :image, 'Archivo' %>
						<%= link_to("", "#", class: "upload_button") %>
            <%= f.cl_image_upload(:image, return_delete_token: true) %>
            <span>Requerido</span><br>
            <span class="status"></span>
          </div>
          <div class="success">
            <%= f.submit "Actualizar", class: "btn btn-lg btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<!-- Configure Cloudinary jQuery plugin -->
<%= cloudinary_js_config %>

<script>
  $(document).ready(function() {
    $(".cloudinary-fileupload")
      .cloudinary_fileupload({
        // Uncomment the following lines to enable client side image resizing and valiation.
        // Make sure cloudinary/processing is included the js file
        //disableImageResize: false,
        //imageMaxWidth: 800,
        //imageMaxHeight: 600,
        //acceptFileTypes: /(\.|\/)(gif|jpe?g|png|bmp|ico)$/i,
        //maxFileSize: 20000000, // 20MB
        dropZone: "#direct_upload",
        start: function (e) {
          $(".status").text("Iniciando carga...");
        },
        progress: function (e, data) {
          $(".status").text("Cargando... " + Math.round((data.loaded * 100.0) / data.total) + "%");
        },
        fail: function (e, data) {
          $(".status").text("La carga falló");
        }
      })
      .off("cloudinarydone").on("cloudinarydone", function (e, data) {
        $("#photo_bytes").val(data.result.bytes);
        $(".status").text("");
        var preview = $(".preview").html('');
        $.cloudinary.image(data.result.public_id, {
          format: data.result.format, width: 50, height: 50, crop: "fit"
        }).appendTo(preview);

        $('<a/>').
          addClass('delete_by_token').
          attr({href: '#'}).
          data({delete_token: data.result.delete_token}).
          html('&times;').
          appendTo(preview).
          click(function(e) {
            e.preventDefault();
            $.cloudinary.delete_by_token($(this).data('delete_token')).done(function(){
              $('.preview').html('');
              $('#info').html('');
              $("#photo_bytes").val('');
              $('input[name="photo[image]"]').remove();
            }).fail(function() {
              $('.status').text("Cannot delete image");
          });
        });
      });
    });
</script>

app/views/images/index.html.erb
<section id="galeria">
	<div class="gallery-container">

	</div>
</section>

<div id="modal-window" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" type="button" data-dismiss="modal" aria-hidden="true"></button>
			</div>
			<div id="image-modal-content" class="modal-body">
			</div>
		</div>
	</div>
</div>

app/views/images/new.html.erb
<section id="nueva-imagen">
  <div class="container form-container">
    <div class="row">
      <div class="col-xs-12">
        <h1>Subir imágen</h1>

        <% if @image.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@image.errors.count, "error") %> no permitieron que esta imágen se halla guardado:</h2>

            <ul>
            <% @image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_for(@image, html: {id: "new-image-form"}) do |f| %>
          <div class="form-group">
            <%= f.label :title, 'Título' %>
            <%= f.text_field :title, placeholder: "Título de la imágen", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :image, 'Archivo' %>
						<%= link_to("", "#", class: "upload_button") %>
            <%= f.cl_image_upload(:image, return_delete_token: true) %>
            <span>Requerido</span><br>
            <span class="status"></span>
          </div>
          <div class="success">
            <%= f.submit "Guardar", class: "btn btn-lg btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<!-- Configure Cloudinary jQuery plugin -->
<%= cloudinary_js_config %>

<script>
  $(document).ready(function() {
    $(".cloudinary-fileupload")
      .cloudinary_fileupload({
        // Uncomment the following lines to enable client side image resizing and valiation.
        // Make sure cloudinary/processing is included the js file
        //disableImageResize: false,
        //imageMaxWidth: 800,
        //imageMaxHeight: 600,
        //acceptFileTypes: /(\.|\/)(gif|jpe?g|png|bmp|ico)$/i,
        //maxFileSize: 20000000, // 20MB
        dropZone: "#direct_upload",
        start: function (e) {
          $(".status").text("Iniciando carga...");
        },
        progress: function (e, data) {
          $(".status").text("Cargando... " + Math.round((data.loaded * 100.0) / data.total) + "%");
        },
        fail: function (e, data) {
          $(".status").text("La carga falló");
        }
      })
      .off("cloudinarydone").on("cloudinarydone", function (e, data) {
        $("#photo_bytes").val(data.result.bytes);
        $(".status").text("");
        var preview = $(".preview").html('');
        $.cloudinary.image(data.result.public_id, {
          format: data.result.format, width: 50, height: 50, crop: "fit"
        }).appendTo(preview);

        $('<a/>').
          addClass('delete_by_token').
          attr({href: '#'}).
          data({delete_token: data.result.delete_token}).
          html('&times;').
          appendTo(preview).
          click(function(e) {
            e.preventDefault();
            $.cloudinary.delete_by_token($(this).data('delete_token')).done(function(){
              $('.preview').html('');
              $('#info').html('');
              $("#photo_bytes").val('');
              $('input[name="photo[image]"]').remove();
            }).fail(function() {
              $('.status').text("Cannot delete image");
          });
        });
      });
    });
</script>

app/views/images/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-center">
        <% if @image.title != "" %>
          <div class="page-header">
            <h1><%= @image.title %></h1>
          </div>
        <% end %>
        <div class="page-content">
          <%= image_tag(@image.route) %>
        </div>
      </div>
    </div>
    <%= link_to 'Regresar a la galería', gallery_path, class: "btn btn-lg btn-success" %>
  </div>
</section>

app/views/presentations/edit.html.erb
<section>
  <div class="container form-container">
    <div class="col-xs-12">
      <h2>Editar presentación</h2>

      <% if @presentation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@presentation.errors.count, "error") %> no permitieron que esta presentación se halla editado:</h2>

          <ul>
          <% @presentation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for(@presentation, html: {id: "new-presentation-form"}) do |f| %>
        <div class="form-group">
          <%= f.label :title, "Nombre de la presentación" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :site, "Lugar" %>
          <%= f.text_field :site, class: "form-control" %>
          <span>Requerido</span>
        </div>
        <div class="form-group">
          <%= f.label :datetime, "Fecha" %><br>
          <%= f.datetime_select :datetime, selected: Date.today %>
          <span>Requerido</span>
        </div>
        <div class="form-group">
          <%= f.label :comment, "Comentarios" %>
          <%= f.text_area :comment, class: "form-control" %>
        </div>
        <div class="success">
          <%= f.submit 'Actualizar', class: "btn btn-lg btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/presentations/index.html.erb
<section id="presentaciones">
  <% if @presentations != [] %>
    <div class="text-center">
      <h2>Proximamente en</h2>
    </div>
    <ul class="tl-frame">
      <% @presentations.each do |p| %>
      <li <% if p.datetime.today? %>class="active"<% end %>>
        <% f = p.datetime %>
        <p class="tl-title"><%= l(f, format: "%B %d") %></p>
        <p><strong><%= p.title %></strong></p>
        <p><strong>Lugar: </strong><%= p.site %></p>
        <p><strong>Hora: </strong><%= l(f, format: '%I:%M %p') %></p>

        <% if p.contributors != nil %>
          <p><strong>Colaboran: </strong><%= p.contributors %></p>
        <% end %>

        <% if p.comment != "" %>
          <p><%= p.comment %></p>
        <% end %>
        <% if user_signed_in? %>
          <ul class="control-panel">
            <li><%= link_to('Editar', edit_presentation_path(p), class: "btn control-btn") %></li>
            <li><%= link_to('Eliminar', p, method: :delete, data: {confirm: "¿Está seguro/a?"}, class: "btn control-btn") %></li>
          </ul>
        <% end %>
      </li>
      <% end %>
    </ul>
  <% else %>
		<div class="section-content">
			<p>Por ahora no tenemos presentaciones.</p>
		</div>
  <% end %>
</section>

app/views/presentations/new.html.erb
<section>
  <div class="container form-container">
    <div class="col-xs-12">
      <h1>Publicar presentación</h1>

      <% if @presentation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@presentation.errors.count, "error") %> no permitieron que esta presentación se halla publicado:</h2>

          <ul>
          <% @presentation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for(@presentation, html: {id: "new-presentation-form"}) do |f| %>
        <div class="form-group">
          <%= f.label :title, "Título" %>
          <%= f.text_field :title, placeholder: "Título de la presentación", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :site, "Lugar" %>
          <%= f.text_field :site, placeholder: "Lugar de la presentación", class: "form-control" %>
          <span>Requerido</span>
        </div>
        <div class="form-group">
          <%= f.label :datetime, "Fecha y hora" %><br>
          <%= f.datetime_select :datetime, selected: Date.today %>
          <span>Requerido</span>
        </div>
        <div class="form-group">
          <%= f.label :comment, "Comentarios" %>
          <%= f.text_area :comment, placeholder: "Comentarios", class: "form-control" %>
        </div>
        <div class="success">
          <%= f.submit 'Guardar', class: "btn btn-lg btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/videos/index.html.erb
<section id="videos">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <% if @videos != [] %>
          <% @videos.each do |video| -%>
            <div class="page-header">
              <h3><%= video.title %></h3>
            </div>
            <div class="page-content">
              <div class="embed-container">
                <%= embed(video.route) %>
              </div>
            </div>
            <% if user_signed_in? %>
              <%= link_to 'Editar', edit_video_path(video), class: "btn btn-md btn-primary" %>
              <%= link_to 'Eliminar', video, method: :delete, data: { confirm: "¿Estas segur@?" }, class: "btn btn-md btn-primary" %>
            <% end %>
          <% end %>
        <% else %>
					<div class="page-content">
						<p>Aun no hay videos disponibles.</p>
					</div>
        <% end %>
      </div>
    </div>
  </div>
</section>