config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  root 'home#index'
 
  resources :comments
  resources :images
  resources :messages
  resources :presentations
  resources :videos
 
  get '/galeria' => 'images#index', as: 'gallery'
  get '/terminos' => 'home#terms', as: 'terms'
  get '/subir_imagen' => 'images#new', as: 'upload_img'
  get '/admin' => 'home#admin', as: 'admin'
 
  post '/create_message' => 'messages#create', as: 'create_message'
  post '/create_comment' => 'comments#create', as: 'create_comment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, presence: true
  validates :message, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  attr_accessor :title, :bytes, :image, :image_cache

  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { minumum: 4, maximum: 80 }
  validates :email, presence: true
  validates :text, presence: true
end

app/models/presentation.rb
class Presentation < ApplicationRecord
  validates :site, presence: true
  validates :datetime, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def authenticate_admin_key(key)
    if key == "anmariazea2017"
      return true
    else
      return false
    end
  end
end

app/models/video.rb
class Video < ApplicationRecord
  validates :route, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html
        format.json { render json: @comment.to_json }
      else
        format.html { render redirect_to: '/' }
        format.json { render json: @comment.errors }
      end
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end
  def index
    @comments = Comment.order(created_at: :desc)
  end
  def new
    @comment = Comment.new
  end
  def show
    @comment = Comment.find(params[:id])
  end

  private
    def comment_params
      params.require(:comment).permit(:name, :email, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = Message.new
    @images = Image.all().limit(5)
  end
  def terms
  end
  def admin
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
		puts image_params
    @image = Image.new(image_params)
    if !@image.save
      @error = @image.errors.full_messages.join('. ')
    end
    redirect_to gallery_path
  end
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    redirect_to gallery_path
  end
  def edit
    @image = Image.find(params[:id])
  end
  def index
		@images = Image.all
		respond_to do |format|
			format.html # Show index.html.erb
			format.json { render json: [@images, user_signed_in?] }
		end
  end
  def new
    @image = Image.new(title: "Imagen\##{1 + (Image.maximum(:id) || 0)}")
  end
  def show
    @image = Image.find(params[:id])
		respond_to do |format|
			format.json { render json: @image }
		end
  end
  def update
    @image = Image.find(params[:id])
    @image.update(image_params)

    redirect_to gallery_path
  end

  protected
  def direct_upload_mode?
    params[:direct].present?
  end

  def unsigned_mode?
    params[:unsigned].present?
  end

  private
    def image_params
      params.require(:image).permit(:image, :title)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to home_path, notice: "{parama[:name]} Su mensaje ha sido enviado" }
        format.json { render json: @message.to_json }
      else
        format.html { render redirect_to: '/' }
        format.json { render json: @message.errors }
      end
    end
  end
  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_path
  end
  def index
    @messages = Message.all
  end
  def new
    @message = Message.new
  end
  def show
    @message = Message.find(params[:id])
  end

  private
    def message_params
      params.require(:message).permit(:name, :email, :number, :text)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def create
    @video = Video.new(video_params)
    @video.save
    redirect_to videos_path
  end
  def destroy
    @video = Video.find(params[:id])
    @video.destroy
  end
  def edit
    @video = Video.find(params[:id])
  end
  def index
     @videos = Video.order(created_at: :desc)
  end
  def new
    @video = Video.new
  end
  def show
    @video = Video.find(params[:id])
  end
  def update
    @video = Video.find(params[:id])
    @video.update(video_params)

    redirect_to videos_path
  end

  private
    def video_params
      params.require(:video).permit(:title, :route, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def embed(url)
    url = url.to_s
    if url.include? "youtu"
      youtube_id = url.split("/").last
      puts youtube_id
      content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}", frameborder: "0")
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta name="keywords" content="musical, maria del carmen zea, navidad, alegria navideña">
    <meta name="author" content="Alvaro Carmona Zapata">
    <meta name="description" content="Hechale un vistazo a mi musical navideño.">
    <title>Musical Alegría Navideña</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
    <body>
      <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Activar navegacion</span> Menú <i class="fa fa-bars"></i>
          </button>

          <%= link_to "Alegría Navideña", root_path, class: "navbar-brand page-scroll" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  *Administrador*
                  <span class="caret">
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Subir imágen', new_image_path %></li>
                  <li><%= link_to 'Crear presentación', new_presentation_path %></li>
                  <li><%= link_to 'Crear video', new_video_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <li class="hidden">
              <a href="#page-top"></a>
            </li>
            <li id="galeria">
              <%= link_to 'Galería', gallery_path %>
            </li>
            <li id="videos">
              <%= link_to 'Videos', videos_path %>
            </li>
            <li id="agenda">
              <%= link_to 'Agenda', presentations_path %>
            </li>
            <li id="comentarios">
              <%= link_to 'Comentarios', comments_path %>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>

    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Alegría Navideña 2017</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li><a href="https://www.facebook.com/profile.php?id=100010104935370&fref=ts"><i class="fa fa-facebook"></i></a>
              </li>
              <li><a href="https://www.youtube.com/channel/UCshMtSLNZ-gYQ5jGOmu_FhA"><i class="fa fa-youtube"></i></a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li>
                <%= link_to 'Terminos de uso', terms_path %></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>